### PR TITLE
Added LICENSE.md

### PR DESCRIPTION
**Pull request by Vani177**

### CODE REVIEW

**Comment by Vani177** [comment]
hey, I need the hactoberfest accepted and hactoberfest labels? Would you mind adding them?

**Comment by Vani177** [comment]
hey @nitishhsinghhh 
I need the hactoberfest and hactoberfest accepted labels on the issue and the PR, do you mind adding those?
I hope not, thanks :)

**Comment by nitishhsinghhh** [comment]
I'm traveling with limited internet connectivity... I'll get back to you soon.Cheers 21:54, 7 October 2023, Vani Sharma ***@***.***>:
hey @nitishhsinghhh
I need the hactoberfest and hactoberfest accepted labels on the issue and the PR, do you mind adding those?
I hope not, thanks :)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by Vani177** [comment]
Oh sure, safe travel!

**Pull request merged**
